#ifndef __DOORBELL_CONFIG_H__
#define __DOORBELL_CONFIG_H__

#define LED_STRIP_GPIO_PIN 46


#define CODEC_I2C_SDA_GPIO_PIN 0
#define CODEC_I2C_SCL_GPIO_PIN 1

#define CODEC_I2S_BCK_GPIO_PIN 2
#define CODEC_I2S_MCK_GPIO_PIN 3
#define CODEC_I2S_DI_GPIO_PIN 4
#define CODEC_I2S_WS_GPIO_PIN 5
#define CODEC_I2S_DO_GPIO_PIN 6

#define CODEC_I2S_SAMPLE_RATE 16000

#define CODEC_PA_GPIO_PIN 7


typedef enum BUTTON_STATUS{
    BUTTON_STATUS_SING,
    BUTTON_STATUS_DOUBLE,
    BUTTON_STATUS_LONG,
}BUTTON_STATUS_T;

#endif /* __DOORBELL_CONFIG_H__ */
